- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: install python
  ansible.builtin.import_role:
    name: common
    tasks_from: python 



- name: start and enable catalogue
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd
    