- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: install golang
  ansible.builtin.import_role:
    name: common
    tasks_from: golang

- name: start and enable catalogue
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd
    