- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: install nodejs
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs  

- name: mongodb setup
  ansible.builtin.import_role:
    name: common
    tasks_from: mongodb-setup

- name: start and enable catalogue
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd
    