- name: copy mongodb.repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: install mongodb clinet
  ansible.builtin.package:
    name: mongodb-org-shell
    state: present 

- name: get the categories proudcts count
  ansible.builtin.command: mongo --host mongodb.gopisri.cloud --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
  register: products_count
  when: component == "catalogue"

- name: get the categories users count
  ansible.builtin.command: mongo --host mongodb.gopisri.cloud --quiet --eval 'db = db.getSiblingDB("users"); db.users.count()'
  register: users_count
  when: component == "user"  

# - name: print the count
#   ansible.builtin.debug:
#     msg: "products_count: {{products_count}}"

- name: "load catalogue data"
  ansible.builtin.command: "mongo --host mongodb.gopisri.cloud < /app/schema/{{component}}.js"
  when: products_count.stdout == "0" and component == "catalogue" # keep in double quotes
  ignore_errors: true

- name: "load user data"
  ansible.builtin.command: "mongo --host mongodb.gopisri.cloud < /app/schema/{{component}}.js"
  when: users_count.stdout == "0" and component == "user" # keep in double quotes
  ignore_errors: true


